# Generated by Django 3.2.3 on 2021-05-25 21:31

import ClinicModule.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('Internist', 'Internist'), ('Gastrologist', 'Gastrologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Pulmonologist', 'Pulmonologist')], default='Internist', max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PESEL', models.CharField(help_text='Enter the PESEL identificator: ', max_length=11, unique=True, validators=[ClinicModule.validators.validate_patient_pesel])),
                ('address', models.CharField(max_length=64, verbose_name='Address')),
                ('city', models.CharField(default='Olsztyn', max_length=64, verbose_name='City')),
                ('zip_code', models.CharField(default='10117', help_text='Zip code', max_length=5, validators=[ClinicModule.validators.validate_zip_code])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.SlugField(default=ClinicModule.validators.get_random_secret, editable=False, max_length=12, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation the visit.')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of modification the visit.')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Short description (purpose) of the visit.')),
                ('category', models.CharField(choices=[('Initial visit', 'Initial visit'), ('Control visit', 'Control visit'), ('Treatment', 'Symptomatic treatment')], default='Initial visit', max_length=32)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ClinicModule.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ClinicModule.patient')),
            ],
            options={
                'ordering': ['date_added', 'patient'],
            },
        ),
    ]
