# Generated by Django 3.1.7 on 2021-05-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugmedicine',
            options={'ordering': ['drug_title']},
        ),
        migrations.RenameField(
            model_name='drugmedicine',
            old_name='drug',
            new_name='drug_title',
        ),
    ]
