# Generated by Django 3.2.3 on 2021-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0002_auto_20210605_1909'),
        ('ClinicModule', '0002_auto_20210605_1917'),
    ]

    operations = [
    ]
