# Generated by Django 3.1.7 on 2021-05-26 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=128)),
                ('description_of_drug', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['drug'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_day_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VisitRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicModule.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DrugPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicModule.doctor')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_assigned', to='ClinicModule.drugmedicine')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClinicModule.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(blank=True, choices=[('Food allergy', 'Food allergy'), ('Inhalation allergy', 'Inhalation allergy'), ('Contact Allergy', 'Contact Allergy'), ('Injection allergy', 'Injection allergy')], max_length=64)),
                ('allergens_type', models.CharField(blank=True, choices=[('Plant Allergens', 'Plant allergens'), ('Animal Allergens', 'Animal allergens'), ('Chemical Allergens', 'Chemical allergens')], max_length=64)),
                ('allergy_descrption', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicModule.patient')),
            ],
        ),
    ]
