# Generated by Django 3.2.3 on 2021-06-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0002_auto_20210606_1639'),
        ('ClinicModule', '0003_merge_0002_auto_20210605_1909_0002_auto_20210605_1917'),
    ]

    operations = [
    ]
