# Generated by Django 3.1.7 on 2021-05-26 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0003_auto_20210526_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_day_start',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
