# Generated by Django 3.2.3 on 2021-06-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicModule', '0004_merge_20210606_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergens_type',
            field=models.CharField(blank=True, choices=[('Alergeny roślinne', 'Alergeny roślinne'), ('Alergeny zwierzęce', 'Alergeny zwierzęce'), ('Alergeny chemiczne', 'Alergeny chemiczne')], max_length=64),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergy_type',
            field=models.CharField(blank=True, choices=[('Alergia na jadzenie', 'Alergia na jadzenie'), ('Alergia wziewna', 'Alergia wziewna'), ('Alergia kontaktowa', 'Alergia kontaktowa'), ('Alergia na zastrzyki', 'Alergia na zastrzyki')], max_length=64),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Internista', 'Internista'), ('Gastrolog', 'Gastrolog'), ('Okulista', 'Okulista'), ('Pulmonolog', 'Pulmonolog')], default='Internista', max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='category',
            field=models.CharField(choices=[('Wizyta wstępna', 'Wizyta wstępna'), ('Wizyta kontrolona', 'Wizyta kontrolona'), ('Leczenie', 'Leczenie objawowe')], default='Wizyta wstępna', max_length=32),
        ),
    ]
